"""Phase 6: thesis-ready LaTeX fragments for the Phase 5/6 deliverables.

Emits:
    thesis/latex/figuras/generated/nmt_leaderboard_xl.tex
    thesis/latex/figuras/generated/nmt_directional_metrics_xl.tex
    thesis/latex/figuras/generated/nmt_bootstrap_ci_xl.tex
    thesis/latex/figuras/generated/nmt_rare_token_full_xl.tex

These complement the existing v0/v1-pairwise tables emitted by
scripts/generate_nmt_tables.py and reflect the closed leaderboard
across all six runs (v0_xl, v1_bt_xl, v2.0, v2.1, v2.1b, v2.2).
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DASH = "---"


DEFAULT_RUNS = [
    "nllb_bidi_lora_v0_xl",
    "nllb_bidi_lora_v1_bt_xl",
    "nllb_bidi_lora_v2_0_dora_xl",
    "nllb_bidi_lora_v2_1_dora_loraplus_xl",
    "nllb_bidi_lora_v2_1b_loraplus_xl",
    "nllb_bidi_lora_v2_2_bt_iter1_xl",
]

LABELS = {
    "nllb_bidi_lora_v0_xl": r"$v_0$",
    "nllb_bidi_lora_v1_bt_xl": r"$v_{1bt}$ (+BT OPUS)",
    "nllb_bidi_lora_v2_0_dora_xl": r"$v_{2.0}$ DoRA",
    "nllb_bidi_lora_v2_1_dora_loraplus_xl": r"$v_{2.1}$ DoRA+LoRA+",
    "nllb_bidi_lora_v2_1b_loraplus_xl": r"$v_{2.1b}$ LoRA+ $\bigstar$",
    "nllb_bidi_lora_v2_2_bt_iter1_xl": r"$v_{2.2}$ +BT iter1 (Wikipedia)",
}


def _load(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def _fmt(v, fmt=".2f") -> str:
    if v is None:
        return DASH
    try:
        return format(float(v), fmt)
    except (TypeError, ValueError):
        return str(v)


def _dir_avg(metrics: dict, key: str) -> float | None:
    directions = metrics.get("directions", {})
    values = []
    for direction in ("shw2spa", "spa2shw"):
        value = directions.get(direction, {}).get(key)
        if value is not None:
            values.append(float(value))
    if len(values) != 2:
        return None
    return sum(values) / len(values)


def _wrap(prefix: str, body: list[str]) -> str:
    header = [
        f"% Auto-generated by scripts/nmt/74_thesis_tables_phase6.py at "
        f"{dt.datetime.now(dt.UTC).isoformat()}",
        f"% Source: {prefix}",
    ]
    return "\n".join(header + [""] + body) + "\n"


def table_leaderboard(runs: list[str], variant: str) -> str:
    suffix = "_xl" if variant == "xl" else ""
    eval_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"evaluation{suffix}"
    rerank_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"reranking{suffix}"

    body = [
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r"\multirow{2}{*}{Variante} & \multicolumn{3}{c}{chrF++ avg} & "
        r"\multicolumn{3}{c}{Reranked avg} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r" & baseline & reranked & $\Delta$ & BLEU & COMET & BERT-F1 \\",
        r"\midrule",
    ]
    for run in runs:
        base = _load(eval_dir / run / "test_metrics.json") or {}
        rer = _load(rerank_dir / run / "test_metrics_reranked.json") or {}
        ba = base.get("avg_chrf_pp")
        ra = rer.get("avg_chrf_pp")
        delta = None if ba is None or ra is None else float(ra) - float(ba)
        bleu = rer.get("avg_bleu")
        comet = _dir_avg(rer, "comet")
        body.append(
            " & ".join(
                [
                    LABELS.get(run, run),
                    _fmt(ba),
                    _fmt(ra),
                    _fmt(delta, "+.2f"),
                    _fmt(bleu),
                    _fmt(comet, ".3f"),
                    _fmt(_dir_avg(rer, "bertscore_f1"), ".3f"),
                ]
            )
            + r" \\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% chrF++ y BLEU son promedios simples entre shw->spa y spa->shw.",
        r"% COMET y BERT-F1 son promedios simples de ambas direcciones; son",
        r"% indicativos porque sus modelos subyacentes no fueron entrenados con shiwilu.",
        r"% $\bigstar$ = variante final seleccionada.",
    ]
    return _wrap(f"leaderboard{suffix} ({len(runs)} runs)", body)


def table_directional_metrics(runs: list[str], variant: str) -> str:
    suffix = "_xl" if variant == "xl" else ""
    rerank_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"reranking{suffix}"

    body = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"\multirow{2}{*}{Variante (reranked)} & "
        r"\multicolumn{2}{c}{shw$\to$spa} & "
        r"\multicolumn{2}{c}{spa$\to$shw} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r" & chrF++ & BLEU & chrF++ & BLEU \\",
        r"\midrule",
    ]
    for run in runs:
        rer = _load(rerank_dir / run / "test_metrics_reranked.json") or {}
        dirs = rer.get("directions", {})
        shw2spa = dirs.get("shw2spa", {})
        spa2shw = dirs.get("spa2shw", {})
        body.append(
            " & ".join(
                [
                    LABELS.get(run, run),
                    _fmt(shw2spa.get("chrf_pp")),
                    _fmt(shw2spa.get("bleu")),
                    _fmt(spa2shw.get("chrf_pp")),
                    _fmt(spa2shw.get("bleu")),
                ]
            )
            + r" \\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% Metricas por direccion sobre las salidas reranked del test set.",
        r"% Esta tabla complementa el leaderboard promedio para evitar ocultar",
        r"% asimetrias entre traduccion hacia castellano y hacia shiwilu.",
    ]
    return _wrap(f"directional_metrics{suffix} ({len(runs)} runs)", body)


def table_bootstrap_ci(runs: list[str], variant: str) -> str:
    suffix = "_xl" if variant == "xl" else ""
    eval_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"evaluation{suffix}"
    rerank_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"reranking{suffix}"

    body = [
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Variante (reranked) & avg chrF++ [IC 95\%] & BLEU avg & COMET avg \\",
        r"\midrule",
    ]
    for run in runs:
        bs = _load(eval_dir / run / "bootstrap_ci.json")
        rer = _load(rerank_dir / run / "test_metrics_reranked.json") or {}
        if not bs:
            body.append(f"{LABELS.get(run, run)} & {DASH} & {DASH} & {DASH} \\\\")
            continue
        avg = bs.get("directions", {}).get("avg")
        if avg:
            chrf_cell = (
                f"{_fmt(avg.get('point'))} "
                f"[{_fmt(avg.get('ci95_lo'))}, {_fmt(avg.get('ci95_hi'))}]"
            )
        else:
            chrf_cell = DASH
        body.append(
            " & ".join([
                LABELS.get(run, run),
                chrf_cell,
                _fmt(rer.get("avg_bleu")),
                _fmt(_dir_avg(rer, "comet"), ".3f"),
            ]) + r" \\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% Bootstrap percentil (n=1000) sobre las predicciones reranked del test set",
        r"% (446 items por direccion, 892 total). El IC se calcula solo para chrF++.",
        r"% BLEU y COMET son puntos promedio reranked para contextualizar el ranking.",
        r"% Predicciones extraidas de",
        r"% reports/05_nmt/reranking{suffix}/<run>/test_predictions_reranked.jsonl.",
    ]
    return _wrap(f"bootstrap_ci{suffix} ({len(runs)} runs)", body)


def table_rare_token_full(runs: list[str], variant: str) -> str:
    suffix = "_xl" if variant == "xl" else ""
    eval_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"evaluation{suffix}"

    body = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"\multirow{2}{*}{Variante (reranked)} & "
        r"\multicolumn{2}{c}{shw$\to$spa} & "
        r"\multicolumn{2}{c}{spa$\to$shw} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r" & chrF++ raras $\geq 20\%$ & OOV rec. & chrF++ raras $\geq 20\%$ & OOV rec. \\",
        r"\midrule",
    ]
    for run in runs:
        data = _load(eval_dir / run / "rare_token_analysis_reranked.json")
        if not data:
            body.append(f"{LABELS.get(run, run)} & {DASH} & {DASH} & {DASH} & {DASH} \\\\")
            continue
        dirs = data.get("directions", {})
        def bucket(d):
            return dirs.get(d, {}).get("buckets", {}).get("20pct_or_more", {}).get("chrf_pp")
        def oov(d):
            return dirs.get(d, {}).get("oov", {}).get("recovery_rate")
        body.append(
            " & ".join([
                LABELS.get(run, run),
                _fmt(bucket("shw2spa")),
                _fmt(oov("shw2spa"), ".3f"),
                _fmt(bucket("spa2shw")),
                _fmt(oov("spa2shw"), ".3f"),
            ]) + r" \\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% chrF++ raras = chrF++ restringido al subset con $\geq 20\%$ palabras raras",
        r"% (frecuencia $<5$ en train). OOV rec. = recall de palabras estrictamente",
        r"% out-of-vocabulary en gold que aparecen en la prediccion.",
    ]
    return _wrap(f"rare_token_full{suffix} ({len(runs)} runs)", body)


QUAL_BUCKET_LABELS = {
    "bleu_0_10": r"BLEU $<10$",
    "bleu_10_20": r"$10\le$ BLEU $<20$",
    "bleu_20_plus": r"BLEU $\ge 20$",
    "chrf_0_20": r"chrF++ $<20$",
    "chrf_20_40": r"$20\le$ chrF++ $<40$",
    "chrf_40_plus": r"chrF++ $\ge 40$",
}

QUAL_DIR_LABELS = {
    "shw2spa": r"shw$\to$spa (BLEU)",
    "spa2shw": r"spa$\to$shw (chrF++)",
}


def table_qualitative_buckets(variant: str, run: str) -> str:
    suffix = "_xl" if variant == "xl" else ""
    summary_path = (
        PROJECT_ROOT / "reports" / "05_nmt" / f"evaluation{suffix}"
        / run / "qualitative" / "bucket_summary.json"
    )
    data = _load(summary_path) or {}
    directions = data.get("directions", {})

    body = [
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"Dirección (métrica) & Banda & n & \% & media \\",
        r"\midrule",
    ]
    ordered = [d for d in ("shw2spa", "spa2shw") if d in directions]
    for di, direction in enumerate(ordered):
        buckets = directions[direction].get("buckets", {})
        items = list(buckets.items())
        for bi, (name, st) in enumerate(items):
            head = (
                rf"\multirow{{{len(items)}}}{{*}}{{{QUAL_DIR_LABELS.get(direction, direction)}}}"
                if bi == 0
                else ""
            )
            pct = st.get("pct")
            pct_cell = DASH if pct is None else _fmt(100 * float(pct), ".1f")
            body.append(
                " & ".join([
                    head,
                    QUAL_BUCKET_LABELS.get(name, name),
                    str(st.get("n", DASH)),
                    pct_cell,
                    _fmt(st.get("mean_score")),
                ]) + r" \\"
            )
        if di != len(ordered) - 1:
            body.append(r"\midrule")
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% Distribucion por banda de puntaje por oracion del modelo campeon reranked.",
        r"% shw->spa se puntua con BLEU por oracion; spa->shw con chrF++ por oracion.",
        r"% Cortes segun el umbral de ruido (BLEU<=10 / chrF++<=20). 'media' es el",
        r"% promedio del puntaje por oracion dentro de la banda.",
    ]
    return _wrap(f"qualitative_buckets{suffix} ({run})", body)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--variant", choices=["main", "xl"], default="xl")
    p.add_argument("--runs", nargs="+", default=None)
    p.add_argument(
        "--qualitative-run",
        default="nllb_bidi_lora_v2_1b_loraplus_xl",
        help="Run whose qualitative bucket_summary.json feeds the qualitative table.",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    runs = args.runs or DEFAULT_RUNS
    suffix = "_xl" if args.variant == "xl" else ""

    out_dir = PROJECT_ROOT / "thesis" / "latex" / "figuras" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)

    artifacts = {
        f"nmt_leaderboard{suffix}.tex": table_leaderboard(runs, args.variant),
        f"nmt_directional_metrics{suffix}.tex": table_directional_metrics(runs, args.variant),
        f"nmt_bootstrap_ci{suffix}.tex": table_bootstrap_ci(runs, args.variant),
        f"nmt_rare_token_full{suffix}.tex": table_rare_token_full(runs, args.variant),
        f"nmt_qualitative_buckets{suffix}.tex": table_qualitative_buckets(
            args.variant, args.qualitative_run
        ),
    }
    for name, body in artifacts.items():
        out = out_dir / name
        out.write_text(body, encoding="utf-8")
        print(f"[gen-phase6-tables] wrote {out.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
