"""Phase 6: thesis-ready LaTeX fragments for the Phase 5/6 deliverables.

Emits:
    thesis/latex/figuras/generated/nmt_leaderboard_xl.tex
    thesis/latex/figuras/generated/nmt_bootstrap_ci_xl.tex
    thesis/latex/figuras/generated/nmt_rare_token_full_xl.tex

These complement the existing v0/v1-pairwise tables emitted by
scripts/generate_nmt_tables.py and reflect the closed leaderboard
across all six runs (v0_xl, v1_bt_xl, v2.0, v2.1, v2.1b, v2.2).
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DASH = "---"


DEFAULT_RUNS = [
    "nllb_bidi_lora_v0_xl",
    "nllb_bidi_lora_v1_bt_xl",
    "nllb_bidi_lora_v2_0_dora_xl",
    "nllb_bidi_lora_v2_1_dora_loraplus_xl",
    "nllb_bidi_lora_v2_1b_loraplus_xl",
    "nllb_bidi_lora_v2_2_bt_iter1_xl",
]

LABELS = {
    "nllb_bidi_lora_v0_xl": r"$v_0$",
    "nllb_bidi_lora_v1_bt_xl": r"$v_{1bt}$ (+BT OPUS)",
    "nllb_bidi_lora_v2_0_dora_xl": r"$v_{2.0}$ DoRA",
    "nllb_bidi_lora_v2_1_dora_loraplus_xl": r"$v_{2.1}$ DoRA+LoRA+",
    "nllb_bidi_lora_v2_1b_loraplus_xl": r"$v_{2.1b}$ LoRA+ $\bigstar$",
    "nllb_bidi_lora_v2_2_bt_iter1_xl": r"$v_{2.2}$ +BT iter1 (Wikipedia)",
}


def _load(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def _fmt(v, fmt=".2f") -> str:
    if v is None:
        return DASH
    try:
        return format(float(v), fmt)
    except (TypeError, ValueError):
        return str(v)


def _wrap(prefix: str, body: list[str]) -> str:
    header = [
        f"% Auto-generated by scripts/nmt/74_thesis_tables_phase6.py at "
        f"{dt.datetime.now(dt.UTC).isoformat()}",
        f"% Source: {prefix}",
    ]
    return "\n".join(header + [""] + body) + "\n"


def table_leaderboard(runs: list[str], variant: str) -> str:
    suffix = "_xl" if variant == "xl" else ""
    eval_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"evaluation{suffix}"
    rerank_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"reranking{suffix}"

    body = [
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r"\multirow{2}{*}{Variante} & "
        r"\multicolumn{3}{c}{Baseline} & "
        r"\multicolumn{3}{c}{Reranked (mejor $\alpha$)} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r" & shw$\to$spa & spa$\to$shw & avg & shw$\to$spa & spa$\to$shw & avg \\",
        r"\midrule",
    ]
    for run in runs:
        base = _load(eval_dir / run / "test_metrics.json") or {}
        rer = _load(rerank_dir / run / "test_metrics_reranked.json") or {}
        bs = base.get("directions", {}).get("shw2spa", {}).get("chrf_pp")
        bt = base.get("directions", {}).get("spa2shw", {}).get("chrf_pp")
        ba = base.get("avg_chrf_pp")
        rs = rer.get("directions", {}).get("shw2spa", {}).get("chrf_pp")
        rt = rer.get("directions", {}).get("spa2shw", {}).get("chrf_pp")
        ra = rer.get("avg_chrf_pp")
        body.append(
            " & ".join(
                [
                    LABELS.get(run, run),
                    _fmt(bs), _fmt(bt), _fmt(ba),
                    _fmt(rs), _fmt(rt), _fmt(ra),
                ]
            )
            + r" \\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% chrF++ (sacrebleu, nrefs:1|case:mixed|eff:yes|nc:6|nw:2|space:no|version:2.5.1).",
        r"% $\bigstar$ = campeon enviado del ciclo de tesis.",
    ]
    return _wrap(f"leaderboard{suffix} ({len(runs)} runs)", body)


def table_bootstrap_ci(runs: list[str], variant: str) -> str:
    suffix = "_xl" if variant == "xl" else ""
    eval_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"evaluation{suffix}"

    body = [
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Variante (reranked) & shw$\to$spa chrF++ [IC 95\%] & spa$\to$shw chrF++ [IC 95\%] & avg chrF++ [IC 95\%] \\",
        r"\midrule",
    ]
    for run in runs:
        bs = _load(eval_dir / run / "bootstrap_ci.json")
        if not bs:
            body.append(f"{LABELS.get(run, run)} & {DASH} & {DASH} & {DASH} \\\\")
            continue
        dirs = bs.get("directions", {})
        def cell(d):
            x = dirs.get(d)
            if not x:
                return DASH
            return (
                f"{_fmt(x.get('point'))} "
                f"[{_fmt(x.get('ci95_lo'))}, {_fmt(x.get('ci95_hi'))}]"
            )
        body.append(
            f"{LABELS.get(run, run)} & {cell('shw2spa')} & {cell('spa2shw')} & {cell('avg')} \\\\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% Bootstrap percentil (n=1000) sobre las predicciones reranked del test set",
        r"% (446 items por direccion, 892 total). Predicciones extraidas de",
        r"% reports/05_nmt/reranking{suffix}/<run>/test_predictions_reranked.jsonl.",
    ]
    return _wrap(f"bootstrap_ci{suffix} ({len(runs)} runs)", body)


def table_rare_token_full(runs: list[str], variant: str) -> str:
    suffix = "_xl" if variant == "xl" else ""
    eval_dir = PROJECT_ROOT / "reports" / "05_nmt" / f"evaluation{suffix}"

    body = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"\multirow{2}{*}{Variante (reranked)} & "
        r"\multicolumn{2}{c}{shw$\to$spa} & "
        r"\multicolumn{2}{c}{spa$\to$shw} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r" & chrF++ raras $\geq 20\%$ & OOV rec. & chrF++ raras $\geq 20\%$ & OOV rec. \\",
        r"\midrule",
    ]
    for run in runs:
        data = _load(eval_dir / run / "rare_token_analysis_reranked.json")
        if not data:
            body.append(f"{LABELS.get(run, run)} & {DASH} & {DASH} & {DASH} & {DASH} \\\\")
            continue
        dirs = data.get("directions", {})
        def bucket(d):
            return dirs.get(d, {}).get("buckets", {}).get("20pct_or_more", {}).get("chrf_pp")
        def oov(d):
            return dirs.get(d, {}).get("oov", {}).get("recovery_rate")
        body.append(
            " & ".join([
                LABELS.get(run, run),
                _fmt(bucket("shw2spa")),
                _fmt(oov("shw2spa"), ".3f"),
                _fmt(bucket("spa2shw")),
                _fmt(oov("spa2shw"), ".3f"),
            ]) + r" \\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% chrF++ raras = chrF++ restringido al subset con $\geq 20\%$ palabras raras",
        r"% (frecuencia $<5$ en train). OOV rec. = recall de palabras estrictamente",
        r"% out-of-vocabulary en gold que aparecen en la prediccion.",
    ]
    return _wrap(f"rare_token_full{suffix} ({len(runs)} runs)", body)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--variant", choices=["main", "xl"], default="xl")
    p.add_argument("--runs", nargs="+", default=None)
    return p.parse_args()


def main() -> int:
    args = parse_args()
    runs = args.runs or DEFAULT_RUNS
    suffix = "_xl" if args.variant == "xl" else ""

    out_dir = PROJECT_ROOT / "thesis" / "latex" / "figuras" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)

    artifacts = {
        f"nmt_leaderboard{suffix}.tex": table_leaderboard(runs, args.variant),
        f"nmt_bootstrap_ci{suffix}.tex": table_bootstrap_ci(runs, args.variant),
        f"nmt_rare_token_full{suffix}.tex": table_rare_token_full(runs, args.variant),
    }
    for name, body in artifacts.items():
        out = out_dir / name
        out.write_text(body, encoding="utf-8")
        print(f"[gen-phase6-tables] wrote {out.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
