"""Phase 8c: emit thesis-ready LaTeX table fragments from the JSON reports.

Output directory: thesis/latex/figuras/generated/nmt_*.tex

Each fragment is a \\begin{tabular} block (no \\begin{table} wrapper) so the
thesis chapter can decide whether to wrap it in a `table` float, a
`subtable`, or a plain inline display. All fragments degrade to "—"
placeholders when their source JSON is missing.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path
from typing import Any
from scripts.nmt._paths import resolve_paths

PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = PROJECT_ROOT / "reports" / "05_nmt"
OUT_DIR = PROJECT_ROOT / "thesis" / "latex" / "figuras" / "generated"
DASH = "---"


def _read_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _fmt(v: Any, fmt: str = ".2f") -> str:
    if v is None:
        return DASH
    try:
        return format(float(v), fmt)
    except (TypeError, ValueError):
        return str(v)


def _wrap(prefix: str, body: list[str]) -> str:
    header = [
        f"% Auto-generated by scripts/generate_nmt_tables.py at "
        f"{dt.datetime.now(dt.timezone.utc).isoformat()}",
        f"% Source: {prefix}",
    ]
    return "\n".join(header + [""] + body) + "\n"


def table_canonical_manifest() -> str:
    data = _read_json(REPORTS_DIR / "preprocessing" / "canonical_manifest.json")
    if data is None:
        body = [
            r"\begin{tabular}{lcccc}",
            r"\toprule",
            r"Split & Pares (entrada) & shw\textrightarrow spa & spa\textrightarrow shw & Total \\",
            r"\midrule",
            f"train & {DASH} & {DASH} & {DASH} & {DASH} \\\\",
            f"valid & {DASH} & {DASH} & {DASH} & {DASH} \\\\",
            f"test & {DASH} & {DASH} & {DASH} & {DASH} \\\\",
            r"\midrule",
            f"Total & {DASH} & {DASH} & {DASH} & {DASH} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
        ]
        return _wrap("canonical_manifest.json (missing)", body)

    inputs = data.get("inputs", {})
    outputs = data.get("outputs", {})
    body = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Split & Pares (entrada) & Filas shw\textrightarrow spa & Filas spa\textrightarrow shw & Total \\",
        r"\midrule",
    ]
    total_in = 0
    total_out = 0
    for split in ("train", "valid", "test"):
        n_in = inputs.get(split, {}).get("row_count", 0)
        n_out = outputs.get(split, {}).get("row_count", 0)
        body.append(
            f"{split} & {n_in} & {n_out // 2 if n_out else DASH} & "
            f"{n_out // 2 if n_out else DASH} & {n_out if n_out else DASH} \\\\"
        )
        total_in += n_in
        total_out += n_out
    body += [
        r"\midrule",
        f"Total & {total_in} & {total_out // 2 if total_out else DASH} & "
        f"{total_out // 2 if total_out else DASH} & {total_out if total_out else DASH} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    return _wrap("canonical_manifest.json", body)


def table_semantic_filter() -> str:
    data = _read_json(REPORTS_DIR / "preprocessing" / "semantic_filter.json")
    if data is None:
        body = [
            r"\begin{tabular}{lccc}",
            r"\toprule",
            r"Split & Aceptados & Marcados & Removidos \\",
            r"\midrule",
            f"train & {DASH} & {DASH} & {DASH} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
        ]
        return _wrap("semantic_filter.json (missing)", body)
    train = data.get("splits", {}).get("train", {})
    counts = train.get("label_counts_pairs", {})
    score = train.get("score_stats", {})
    body = [
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Bucket (pares) & Aceptados & Marcados & Removidos \\",
        r"\midrule",
        f"Conteo & {counts.get('accepted', DASH)} & "
        f"{counts.get('flagged_for_review', DASH)} & "
        f"{counts.get('removed', DASH)} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
        f"% train cosine score: mean = {_fmt(score.get('mean'), '.4f')}, "
        f"std = {_fmt(score.get('std'), '.4f')}, "
        f"min = {_fmt(score.get('min'), '.4f')}, "
        f"max = {_fmt(score.get('max'), '.4f')}",
    ]
    return _wrap("semantic_filter.json", body)


def _avg_tokens_per_word(examples: list[dict], key: str) -> float | None:
    """Average tokens-per-word across the example sentences, using whitespace
    word count of the original sentence as denominator."""
    if not examples:
        return None
    totals_tokens = 0
    totals_words = 0
    for ex in examples:
        sent = str(ex.get("sentence", ""))
        n_words = len([w for w in sent.split() if w])
        if n_words == 0:
            continue
        n_tokens = ex.get(key, {}).get("n", 0)
        totals_tokens += int(n_tokens)
        totals_words += n_words
    if totals_words == 0:
        return None
    return totals_tokens / totals_words


def _fragmentation_ratio(examples: list[dict]) -> tuple[int, int, int]:
    """Returns ``(sp_shorter, equal, nllb_shorter)`` over the examples.

    Counts how often each tokenizer produces fewer tokens for a Shiwilu
    sentence. A higher ``sp_shorter`` count is the empirical justification for
    not adopting NLLB's tokenizer for Shiwilu (we'd amplify fragmentation),
    while the eventual decision to keep NLLB is grounded on transfer learning,
    not subword efficiency.
    """
    sp_shorter = 0
    equal = 0
    nllb_shorter = 0
    for ex in examples:
        sp_n = int(ex.get("sp_unigram_8k", {}).get("n", 0))
        nllb_n = int(ex.get("nllb", {}).get("n", 0))
        if sp_n < nllb_n:
            sp_shorter += 1
        elif sp_n == nllb_n:
            equal += 1
        else:
            nllb_shorter += 1
    return sp_shorter, equal, nllb_shorter


def table_sentencepiece_vs_nllb() -> str:
    data = _read_json(REPORTS_DIR / "preprocessing" / "sentencepiece_stats.json")
    if data is None:
        body = [
            r"\begin{tabular}{lcccc}",
            r"\toprule",
            r"Tokenizador & Tokens / frase & Tokens / palabra & Vocab efectivo & Frases m\'as cortas \\",
            r"\midrule",
            f"SP Unigram & {DASH} & {DASH} & {DASH} & {DASH} \\\\",
            f"NLLB-200 & {DASH} & {DASH} & {DASH} & {DASH} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
        ]
        return _wrap("sentencepiece_stats.json (missing)", body)
    sp = data.get("sentencepiece", {})
    cmp = data.get("comparison", {})
    examples = cmp.get("examples", []) or []
    sample_size = cmp.get("sample_size", len(examples))
    sp_per_word = _avg_tokens_per_word(examples, "sp_unigram_8k")
    nllb_per_word = _avg_tokens_per_word(examples, "nllb")
    sp_short, equal, nllb_short = _fragmentation_ratio(examples)

    body = [
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Tokenizador & Tokens / frase & Tokens / palabra & Vocab efectivo & "
        r"Frases m\'as cortas \\",
        r"\midrule",
        f"SP Unigram (este trabajo) & {_fmt(cmp.get('sp_unigram_avg_tokens'))} & "
        f"{_fmt(sp_per_word)} & {sp.get('actual_vocab_size', DASH)} & "
        f"{sp_short}/{sample_size} \\\\",
        f"NLLB-200 & {_fmt(cmp.get('nllb_avg_tokens'))} & "
        f"{_fmt(nllb_per_word)} & 256\\,000 & {nllb_short}/{sample_size} \\\\",
        r"\midrule",
        f"Empate & {DASH} & {DASH} & {DASH} & {equal}/{sample_size} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
        f"% Sample size: {sample_size} oraciones Shiwilu (seed={cmp.get('sample_seed', DASH)}).",
    ]
    return _wrap("sentencepiece_stats.json", body)


def _read_rare_token(run: str, reranked: bool = False) -> dict | None:
    suffix = "_reranked" if reranked else ""
    return _read_json(REPORTS_DIR / "evaluation" / run / f"rare_token_analysis{suffix}.json")


def _rare_row(label: str, data: dict | None) -> str:
    if data is None:
        return (
            f"{label} & {DASH} & {DASH} & {DASH} & {DASH} & {DASH} & {DASH} \\\\"
        )
    dirs = data.get("directions", {})

    def _b(direction: str, key: str, fmt: str = ".2f") -> str:
        body_d = dirs.get(direction, {})
        bucket = body_d.get("buckets", {}).get("20pct_or_more", {})
        if not bucket:
            return DASH
        return _fmt(bucket.get(key), fmt)

    def _o(direction: str, fmt: str = ".3f") -> str:
        body_d = dirs.get(direction, {})
        oov = body_d.get("oov", {})
        if not oov:
            return DASH
        return _fmt(oov.get("recovery_rate"), fmt)

    return (
        f"{label} & {_b('shw2spa', 'chrf_pp')} & {_o('shw2spa')} & "
        f"{_b('spa2shw', 'chrf_pp')} & {_o('spa2shw')} & "
        f"{_fmt(data.get('avg_rare_chrf_pp_20pct_or_more'))} & "
        f"{_fmt(data.get('avg_oov_recovery_rate'), '.3f')} \\\\"
    )


def table_rare_token(v0: str = "nllb_bidi_lora_v0", v1: str = "nllb_bidi_lora_v1_bt") -> str:
    """Rare-token / morphology-aware comparison across systems."""
    sources = {
        f"{v0}": _read_rare_token(v0, reranked=False),
        f"{v0}+rerank": _read_rare_token(v0, reranked=True),
        f"{v1}": _read_rare_token(v1, reranked=False),
        f"{v1}+rerank": _read_rare_token(v1, reranked=True),
    }
    body: list[str] = [
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r"\multirow{2}{*}{Variante} & "
        r"\multicolumn{2}{c}{shw\textrightarrow spa} & "
        r"\multicolumn{2}{c}{spa\textrightarrow shw} & "
        r"\multicolumn{2}{c}{Promedio} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
        r" & chrF++ raras & OOV rec. & chrF++ raras & OOV rec. & chrF++ raras & OOV rec. \\",
        r"\midrule",
    ]
    for label, data in sources.items():
        body.append(_rare_row(label.replace("_", r"\_"), data))
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% chrF++ raras = chrF++ sobre el bucket de referencias con $\geq 20\%$ palabras",
        r"% raras (frecuencia $<5$ en train); OOV rec. = fraccion de palabras OOV en gold",
        r"% que aparecen tambien en la prediccion (ver scripts/nmt/41\_rare\_token\_eval.py).",
    ]
    return _wrap("rare_token_analysis{,_reranked}.json", body)


def _maybe_metrics(metrics: dict | None, direction: str, name: str, fmt: str = ".2f") -> str:
    if metrics is None:
        return DASH
    d = metrics.get("directions", {}).get(direction, {})
    return _fmt(d.get(name), fmt)


def table_run_comparison(v0: str = "nllb_bidi_lora_v0", v1: str = "nllb_bidi_lora_v1_bt") -> str:
    eval_dir = REPORTS_DIR / "evaluation"
    rerank_dir = REPORTS_DIR / "reranking"
    sources = {
        f"{v0}": _read_json(eval_dir / v0 / "test_metrics.json"),
        f"{v0}+rerank": _read_json(rerank_dir / v0 / "test_metrics_reranked.json"),
        f"{v1}": _read_json(eval_dir / v1 / "test_metrics.json"),
        f"{v1}+rerank": _read_json(rerank_dir / v1 / "test_metrics_reranked.json"),
    }
    body: list[str] = [
        r"\begin{tabular}{lcccccccc}",
        r"\toprule",
        r"\multirow{2}{*}{Variante} & \multicolumn{4}{c}{shw\textrightarrow spa} & "
        r"\multicolumn{4}{c}{spa\textrightarrow shw} \\",
        r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}",
        r" & chrF++ & BLEU & BERTScore & COMET & chrF++ & BLEU & BERTScore & COMET \\",
        r"\midrule",
    ]
    for label, m in sources.items():
        body.append(
            " & ".join(
                [
                    label.replace("_", r"\_"),
                    _maybe_metrics(m, "shw2spa", "chrf_pp"),
                    _maybe_metrics(m, "shw2spa", "bleu"),
                    _maybe_metrics(m, "shw2spa", "bertscore_f1", ".3f"),
                    _maybe_metrics(m, "shw2spa", "comet", ".3f"),
                    _maybe_metrics(m, "spa2shw", "chrf_pp"),
                    _maybe_metrics(m, "spa2shw", "bleu"),
                    _maybe_metrics(m, "spa2shw", "bertscore_f1", ".3f"),
                    _maybe_metrics(m, "spa2shw", "comet", ".3f"),
                ]
            )
            + r" \\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
    ]
    return _wrap("test_metrics{,_reranked}.json", body)


def table_alpha_ablation(run: str = "nllb_bidi_lora_v0") -> str:
    data = _read_json(REPORTS_DIR / "reranking" / run / "ablation.json")
    if data is None:
        body = [
            r"\begin{tabular}{lcc}",
            r"\toprule",
            r"$\alpha$ (translation) & avg chrF++ & avg BLEU \\",
            r"\midrule",
            f"0.00 & {DASH} & {DASH} \\\\",
            f"0.30 & {DASH} & {DASH} \\\\",
            f"0.50 & {DASH} & {DASH} \\\\",
            f"0.70 & {DASH} & {DASH} \\\\",
            f"1.00 & {DASH} & {DASH} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
        ]
        return _wrap(f"ablation.json (missing) for {run}", body)
    body = [
        r"\begin{tabular}{lcc}",
        r"\toprule",
        r"$\alpha$ (translation) & avg chrF++ & avg BLEU \\",
        r"\midrule",
    ]
    for key, item in data.get("by_alpha", {}).items():
        a = item.get("alpha")
        body.append(
            f"{a:.2f} & {_fmt(item.get('avg_chrf_pp'))} & {_fmt(item.get('avg_bleu'))} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}"]
    return _wrap(f"ablation.json for {run}", body)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--variant", choices=["main", "xl"], default="main")
    p.add_argument("--v0", default="nllb_bidi_lora_v0")
    p.add_argument("--v1", default="nllb_bidi_lora_v1_bt")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    nmt_paths = resolve_paths(PROJECT_ROOT, args.variant)
    suffix = "_xl" if args.variant == "xl" else ""
    global REPORTS_DIR
    REPORTS_DIR = PROJECT_ROOT / "reports" / "05_nmt"
    global OUT_DIR
    OUT_DIR = PROJECT_ROOT / "thesis" / "latex" / "figuras" / "generated"
    # variant-aware report roots
    REPORTS_DIR = REPORTS_DIR / f"{''}"  # no-op for readability
    if args.variant == "xl":
        # this script expects the phase folders directly under REPORTS_DIR
        # (preprocessing, evaluation, reranking), so we rewrite the lookup roots
        # through symlink-like shadow names.
        pass

    # monkeypatch per-variant lookups by redirecting _read_json calls through
    # the variant-specific phase directories
    base_reports = PROJECT_ROOT / "reports" / "05_nmt"
    preprocessing_dir = base_reports / ("preprocessing_xl" if args.variant == "xl" else "preprocessing")
    evaluation_dir = base_reports / ("evaluation_xl" if args.variant == "xl" else "evaluation")
    reranking_dir = base_reports / ("reranking_xl" if args.variant == "xl" else "reranking")

    def _rewrite(path: Path) -> Path:
        s = str(path)
        s = s.replace(str(base_reports / "preprocessing"), str(preprocessing_dir))
        s = s.replace(str(base_reports / "evaluation"), str(evaluation_dir))
        s = s.replace(str(base_reports / "reranking"), str(reranking_dir))
        return Path(s)

    original_read_json = _read_json

    def _read_json_variant(path: Path) -> dict | None:
        return original_read_json(_rewrite(path))

    globals()["_read_json"] = _read_json_variant

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    artifacts = {
        f"nmt_canonical_manifest{suffix}.tex": table_canonical_manifest(),
        f"nmt_semantic_filter{suffix}.tex": table_semantic_filter(),
        f"nmt_sentencepiece_vs_nllb{suffix}.tex": table_sentencepiece_vs_nllb(),
        f"nmt_run_comparison{suffix}.tex": table_run_comparison(args.v0, args.v1),
        f"nmt_alpha_ablation_v0{suffix}.tex": table_alpha_ablation(args.v0),
        f"nmt_alpha_ablation_v1{suffix}.tex": table_alpha_ablation(args.v1),
        f"nmt_rare_token{suffix}.tex": table_rare_token(args.v0, args.v1),
    }
    for name, body in artifacts.items():
        out = OUT_DIR / name
        out.write_text(body, encoding="utf-8")
        print(f"[gen-nmt-tables] {out.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
